name: rusty-paper-wallet

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:

  cosmetics:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings

  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly, 1.46.0]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo build --all
